# Generated by Django 4.2.21 on 2025-05-24 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=15, unique=True, verbose_name='Número de Matrícula')),
                ('model', models.CharField(max_length=50, verbose_name='Modelo')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('year', models.PositiveIntegerField(verbose_name='Año de Fabricación')),
                ('capacity', models.CharField(blank=True, max_length=50, null=True, verbose_name='Capacidad de Carga')),
                ('registration_date', models.DateField(verbose_name='Fecha de Inicio de Actividades')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='Último Mantenimiento')),
                ('total_fuel_consumption', models.FloatField(default=0.0, verbose_name='Consumo Total de Combustible (Litros)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
            ],
            options={
                'verbose_name': 'Camión',
                'verbose_name_plural': 'Camiones',
                'ordering': ['plate_number'],
            },
        ),
        migrations.CreateModel(
            name='TruckTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Viaje')),
                ('end_load_time', models.TimeField(default=django.utils.timezone.now, verbose_name='Hora de Finalización de Carga')),
                ('load_type', models.CharField(choices=[('A', 'Carga A'), ('B', 'Carga B'), ('C', 'Carga C')], max_length=1, verbose_name='Tipo de Carga')),
                ('load_location', models.CharField(choices=[('LA', 'Lugar A'), ('LB', 'Lugar B'), ('LC', 'Lugar C')], max_length=2, verbose_name='Lugar de Carga')),
                ('unload_location', models.CharField(choices=[('D1', 'Descarga 1'), ('D2', 'Descarga 2'), ('D3', 'Descarga 3')], max_length=2, verbose_name='Lugar de Descarga')),
                ('mileage', models.PositiveIntegerField(verbose_name='Kilometraje al Cargar Combustible')),
                ('fuel_loaded_liters', models.FloatField(verbose_name='Carga Combustible (Litros)')),
                ('fuel_loaded_amount', models.FloatField(verbose_name='Carga Combustible (Importe)')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='cargo.truck', verbose_name='Camión')),
            ],
            options={
                'verbose_name': 'Viaje de Camión',
                'verbose_name_plural': 'Viajes de Camiones',
                'ordering': ['-date', '-end_load_time'],
            },
        ),
        migrations.CreateModel(
            name='TruckDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=30, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('license_number', models.CharField(max_length=20, unique=True, verbose_name='Cédula de Identidad')),
                ('cell_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Número de Celular')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='truck_driver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conductor de Camión',
                'verbose_name_plural': 'Conductores de Camión',
            },
        ),
        migrations.AddField(
            model_name='truck',
            name='driver',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to='cargo.truckdriver', verbose_name='Conductor'),
        ),
    ]
