# Generated by Django 4.2.21 on 2025-06-09 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cargo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truckdriver',
            name='email',
        ),
        migrations.RemoveField(
            model_name='truckdriver',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='truckdriver',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='truckdriver',
            name='cell_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Número de Celular (formato: 09XXXXXXX)'),
        ),
        migrations.AlterField(
            model_name='truckdriver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='truck_driver', to=settings.AUTH_USER_MODEL, verbose_name='Condcutor'),
        ),
    ]
