# Generated by Django 4.2.21 on 2025-06-15 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cargo', '0002_remove_truckdriver_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckdriver',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_drivers', to=settings.AUTH_USER_MODEL),
        ),
    ]
