# Generated by Django 4.2.21 on 2025-06-15 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0003_truckdriver_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckdriver',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
