# Generated by Django 4.2.21 on 2025-06-15 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0004_truckdriver_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truck',
            old_name='model',
            new_name='moddel',
        ),
    ]
