# Generated by Django 4.2.21 on 2025-06-15 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cargo', '0006_alter_truck_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='truck_added_by', to=settings.AUTH_USER_MODEL, verbose_name='Agregado por'),
        ),
    ]
