# Generated by Django 4.2.21 on 2025-07-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0007_truck_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='mileage',
            field=models.PositiveIntegerField(default=0, verbose_name='Kilometraje Actual'),
        ),
    ]
