# Generated by Django 4.2.21 on 2025-07-13 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0008_truck_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trucktrip',
            name='fuel_loaded_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Carga Combustible (Importe)'),
        ),
        migrations.AlterField(
            model_name='trucktrip',
            name='fuel_loaded_liters',
            field=models.FloatField(blank=True, null=True, verbose_name='Carga Combustible (Litros)'),
        ),
    ]
