# Generated by Django 4.2.21 on 2025-07-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0009_alter_trucktrip_fuel_loaded_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trucktrip',
            name='initial_mileage',
            field=models.PositiveIntegerField(default=0, verbose_name='Kilometraje al Iniciar Viaje'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='mileage',
            field=models.PositiveIntegerField(verbose_name='Kilometraje Actual'),
        ),
    ]
