# Generated by Django 4.2.21 on 2025-07-17 21:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0011_alter_truck_mileage'),
    ]

    operations = [
        migrations.AddField(
            model_name='trucktrip',
            name='unload_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hora de Descarga'),
        ),
    ]
