# Generated by Django 4.2.21 on 2025-07-18 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0012_trucktrip_unload_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='trucktrip',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='cargo.truckdriver', verbose_name='Conductor'),
        ),
    ]
