# Generated by Django 4.2.21 on 2025-07-19 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0013_trucktrip_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trucktrip',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='cargo.truckdriver', verbose_name='Conductor'),
        ),
    ]
